language: dart

dist: xenial

# Test can pass without it but as flutter doctor complaints so that's why we are installing it.
addons:
  apt:
    packages:
      - lib32stdc++6

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov

script:
  - ./flutter/bin/flutter test --coverage

after_success:
  - coveralls-lcov coverage/lcov.info

cache:
  directories:
    - $HOME/.pub-cache